### PR TITLE
Value labels

### PR DESCRIPTION
**Pull request by dmbates**
Closes https://github.com/davidanthoff/ReadStat.jl/issues/37

I will add tests later.  I plan to use some of the files from https://github.com/tidyverse/haven but they exercise capabilities recently added in the master tree of https://github.com/WizardMac/ReadStat

### CODE REVIEW

**Comment by davidanthoff** [comment]
Would you suggest I merge this PR first, or wait for you to push some more commits with tests and then merge?

**Comment by dmbates** [comment]
Please go ahead and merge.  I think it will be necessary to wait on a new release of the ReadStat C library to get the new capabilities and use the haven test files.  If you are uncomfortable with making a new release of this package without tests for the value labels I will create a test.

**Comment by davidanthoff** [comment]
No problem, happy to cut a release with the existing tests passing. Just give me a ping when you are done and I'll merge and tag.

I might have some time next week to try to get the new C library compiled and working with the new BinDeps. Last time I tried I got pretty far, I think I just need one more go.

**Comment by dmbates** [comment]
Thanks for waiting.  You can make a release now.

**Pull request merged**
